export const API_ERROR_CODES = {
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_REQUIRE_PASSWORD: "USER_REQUIRE_PASSWORD",
  PERMISSION_ERROR: "PERMISSION_ERROR",
  USER_REQUIRE_PHONE: "USER_REQUIRE_PHONE",
  DUPLICATE_SOCIAL_ID: "DUPLICATE_SOCIAL_ID",
};
