export const PAGE_NAMES = {
  HOME: "/",
  LOGIN: "/login",
  STORE: "/store",
  PRODUCTS: "/products",
  NEWS: "/news",
  SERVICE: "/service",
  PASSWORD_VERIFICATION: "/login/password-verification",
  SEND_OTP: "/login/send-otp",
  VERIFY_PHONE_NUMBER: "/login/verify-phone-number",
  FORGOT_PASSWORD: "/login/forgot-password",
  VERIFY_EMAIL: "/login/verify-email",
  ACCOUNT: "/account",

  MY_VOUCHER: "/account/my-voucher",
  MY_ORDER: "/account/my-order",
  FAVORITES_LIST: "/account/favorites-list",
  INTRODUCE: "/account/introduce",
  ADDRESS: "/account/address",
  SETTING: "/account/setting",
  FEEDBACK: "/account/feedback",
  CHANGE_PASSWORD: "/account/change-password",
  ORDER_DETAIL: "/account/my-order",
  FAVORITE_PRODUCT: "/account/favorite-product",
  CONFIRM_ORDER: "/confirm-order",
  WALLET: "/wallet",
  CHANGE_LANGUAGE: "/account/setting/change-language",
  TOP_UP: "/wallet/top-up",
  PAYMENT_CODE: "/wallet/payment-code",
  TRANSACTION_HISTORY: "/wallet/transaction-history",
  COIN_WALLET: "/coin",
};
