export const REDUX_TYPES = {
  SHOW_APP_LOADING: 'SHOW_APP_LOADING',
  SHOW_APP_POPUP: 'SHOW_APP_POPUP',
  DISMISS_APP_POPUP: 'DISMISS_APP_POPUP',
  SET_TOKEN: 'SET_TOKEN',
  SET_USER: 'SET_USER',
  SET_CHECKIN_CODE: 'SET_CHECKIN_CODE',
  SET_UNREAD_NOTI_COUNT: 'SET_UNREAD_NOTI_COUNT',
  SET_HAS_NEW_VOUCHERS: 'SET_HAS_NEW_VOUCHERS',
  SET_WALLET_INFO : 'SET_WALLET_INFO'
}
